/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Auth;

import dashboard.DashboardPetugas;
import dashboard.DashboardSuperVisor;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Interactive splash screen shown after successful registration
 * Shows success message and user details, then redirects to appropriate dashboard
 * 
 * @author Team SIPRIMA
 */
public class FormSplashScreen extends javax.swing.JFrame {
    
    private String username;
    private String role;
    private Timer redirectTimer;
    private int countdown = 3;
    
    /**
     * Creates new form FormSplashScreen
     */
    public FormSplashScreen() {
        initComponents();
        setLocationRelativeTo(null); // Center the window
    }
    
    /**
     * Creates new form FormSplashScreen with user details
     * @param username The registered username
     * @param role The user's role (Petugas or SuperVisor)
     */
    public FormSplashScreen(String username, String role) {
        this();
        this.username = username;
        this.role = role;
        
        // Update labels with user information
        usernameLabel.setText("Username: " + username);
        roleLabel.setText("Role: " + role);
        
        // Start the countdown timer
        startRedirectTimer();
    }
    
    /**
     * Starts the countdown timer for automatic redirection
     */
    private void startRedirectTimer() {
        redirectTimer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                countdown--;
                
                if (countdown > 0) {
                    redirectLabel.setText("Mengarahkan ke dashboard dalam " + countdown + " detik...");
                } else {
                    redirectLabel.setText("Mengarahkan ke dashboard...");
                    redirectTimer.stop();
                    redirectToDashboard();
                }
            }
        });
        
        redirectTimer.start();
    }
    
    /**
     * Redirects user to appropriate dashboard based on their role
     */
    private void redirectToDashboard() {
        this.dispose(); // Close splash screen
        
        try {
            // Get current user from session manager
            Utils.SessionManager sessionManager = Utils.SessionManager.getInstance();
            models.User currentUser = sessionManager.getCurrentUser();
            
            if (currentUser != null) {
                // Pass user object to dashboard constructor
                if ("SuperVisor".equalsIgnoreCase(role) || "supervisor".equalsIgnoreCase(role)) {
                    new DashboardSuperVisor(currentUser).setVisible(true);
                } else {
                    // Default to DashboardPetugas for all other roles
                    new DashboardPetugas(currentUser).setVisible(true);
                }
            } else {
                System.err.println("❌ No user in session - redirecting to login");
                // Fallback to login if no user session
                new Auth.FormLogin().setVisible(true);
            }
            
        } catch (Exception e) {
            System.err.println("❌ Error redirecting to dashboard: " + e.getMessage());
            e.printStackTrace();
            
            // Fallback to login on error
            new Auth.FormLogin().setVisible(true);
        }
    }
    
    /**
     * Override dispose to stop timer if form is closed manually
     */
    @Override
    public void dispose() {
        if (redirectTimer != null && redirectTimer.isRunning()) {
            redirectTimer.stop();
        }
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splashPanel = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        redirectLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIPRIMA - Registrasi Berhasil");
        setUndecorated(true);

        splashPanel.setBackground(new java.awt.Color(236, 244, 245));
        splashPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 128, 185), 3, true));
        splashPanel.setPreferredSize(new java.awt.Dimension(500, 400));

        iconLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        iconLabel.setForeground(new java.awt.Color(41, 128, 185));
        iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLabel.setText("✓");

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(41, 128, 185));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("REGISTRASI BERHASIL!");

        messageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(44, 62, 80));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("Selamat datang di SIPRIMA Desa Tarabbi!");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(44, 62, 80));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Username: [USERNAME]");

        roleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(127, 140, 141));
        roleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roleLabel.setText("Role: [ROLE]");

        redirectLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        redirectLabel.setForeground(new java.awt.Color(127, 140, 141));
        redirectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redirectLabel.setText("Mengarahkan ke dashboard dalam 3 detik...");

        javax.swing.GroupLayout splashPanelLayout = new javax.swing.GroupLayout(splashPanel);
        splashPanel.setLayout(splashPanelLayout);
        splashPanelLayout.setHorizontalGroup(
            splashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splashPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(splashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redirectLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        splashPanelLayout.setVerticalGroup(
            splashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splashPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(redirectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSplashScreen("TestUser", "Petugas").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel iconLabel;
    public javax.swing.JLabel messageLabel;
    public javax.swing.JLabel redirectLabel;
    public javax.swing.JLabel roleLabel;
    public javax.swing.JPanel splashPanel;
    public javax.swing.JLabel titleLabel;
    public javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}

